### PR TITLE
closes #8 - Fix use group

### LINKED ISSUE #8: remove total volume as a use group

### PR DESCRIPTION
**Pull request by alvizek**
This fixes the `total volume` issue where it was being included as a use group and also fixes another issue with duplicate rows in the use_type_lookup

### CODE REVIEW

File: R/pull_data.R [hunk 1]
```diff
@@ -181,35 +181,70 @@ get_cr_data <- function() {
...
+              )) |>
+    mutate(volume_af = ifelse(is.nan(volume_af), NA, volume_af))
+
+  residential_cr <- conservation_report_data |>
+    filter(category == "demand") |>
+    group_by(report_name, pwsid, supplier_name,
+             year, month, category) |>
+    summarize(total_demand = sum(volume_af, na.rm = TRUE),
+              final_prop_residential = as.numeric(final_percent_residential_use)/100,
+              residential = total_demand * final_prop_residential) |>
```
Comment (alvizek) [inline R/pull_data.R:238]: We need to multiply by total production instead of demand:

- This is our note `% Residential (Can calculate volume residential by `Total Potable Water Production` * `Percent Residential Use`)` from https://github.com/cawaterdata/urban-water-reporting/blob/main/scripts/reports_and_metrics_overview.Rmd
- Data dictionary - https://www.waterboards.ca.gov/water_issues/programs/conservation_portal/docs/definitions_and_data_dictionary_accessible.pdf

**Review by alvizek — COMMENTED** [review]
Thank you for making changes - I think I found the discrepancy.

File: R/pull_data.R (hunk 1 above)
Comment (ErinCain) [reply R/pull_data.R]: updated
